export const projectData = {
  brandMarketing: [
    {
      id: 'ja-timber-brand',
      title: 'JA Timber & Land Clearing',
      description: 'Brand identity, signage, and marketing materials for a land-clearing company. Delivered logo, yard signs, business cards, and full brand guidelines.',
      fullDescription: 'Complete brand identity system for JA Timber & Land Clearing, a land-management company. Designed and produced the full brand package including logo design, yard signs, vehicle graphics, business cards, and comprehensive brand guidelines. Built a cohesive visual language that communicates professionalism and reliability.',
      deliverables: 'Logo design, brand guidelines, business cards, yard signage, vehicle graphics, print collateral',
      category: 'Brand & Marketing',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/2b381c55e_generated_288a1c9a.png',
    },
    {
      id: 'safran-brand',
      title: 'Safran Everyday',
      description: 'Brand positioning and marketing materials for an emerging lifestyle brand. Developed visual identity and campaign assets.',
      fullDescription: 'Developed brand positioning, visual identity, and marketing collateral for Safran Everyday, an emerging lifestyle brand. Created a cohesive brand story and translated it into print and digital assets that reflect the brand\'s warm, modern aesthetic.',
      deliverables: 'Brand strategy, visual identity, print collateral, digital campaign assets',
      category: 'Brand & Marketing',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/67d5a4761_generated_1d72d942.png',
    },
    {
      id: 'brand-marketing-3',
      title: 'Flourish Wellness Co.',
      description: 'Full brand development for a boutique wellness studio — strategy, visual identity, and launch campaign materials.',
      fullDescription: 'End-to-end brand development for Flourish Wellness Co., a boutique studio concept. Led brand strategy sessions, developed the visual identity system, and produced a full suite of launch campaign materials across print and digital.',
      deliverables: 'Brand strategy, logo, color system, print materials, social media templates, launch campaign',
      category: 'Brand & Marketing',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/63190f313_generated_c28d7045.png',
    },
  ],
  websitesDigital: [
    {
      id: 'ja-timber-web',
      title: 'JA Timber — Website',
      description: 'Full website design and build for a land-management business. Structured content, designed UI, and wrote brand messaging.',
      fullDescription: 'Designed and built the full website for JA Timber & Land Clearing. Handled site structure, UI design, responsive layout, brand messaging, and copywriting. Delivered a site that clearly communicates services and drives quote requests.',
      deliverables: 'Website design, responsive development, copywriting, SEO foundations',
      category: 'Websites & Digital',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/dfdec04e6_generated_c1ad4483.png',
    },
    {
      id: 'myco-platform',
      title: 'MyCo',
      description: 'Concept, branding, and digital platform design for an original startup concept. Built the visual identity and interface from the ground up.',
      fullDescription: 'Conceived and designed MyCo, an original digital platform concept. Led all aspects including brand identity, user interface design, and visual strategy. Translated the business concept into a polished, user-centered digital experience.',
      deliverables: 'Concept development, brand identity, UI/UX design, prototype',
      category: 'Websites & Digital',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/09d4a6042_generated_b6581ffe.png',
    },
    {
      id: 'digital-3',
      title: 'Bloom Studio',
      description: 'Website redesign and digital brand refresh for a photography studio. Modernized the visual presence and improved user flow.',
      fullDescription: 'Led a comprehensive website redesign for Bloom Studio, a creative photography business. Modernized the visual identity for digital, restructured the portfolio layout, and improved the user journey from landing to booking.',
      deliverables: 'Website redesign, digital brand refresh, content strategy, booking flow',
      category: 'Websites & Digital',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/eeaaa9dfa_generated_9417aab5.png',
    },
  ],
  productDevelopment: [
    {
      id: 'magic-rescue-stick',
      title: 'Magic Rescue Stick',
      description: 'Consumer product development including manufacturer sourcing, sampling, custom packaging, and brand identity.',
      fullDescription: 'Led the full product development cycle for the Magic Rescue Stick, a consumer product. Managed manufacturer sourcing and vetting, oversaw sampling rounds, designed custom packaging, and developed the brand identity. Took the product from raw concept to shelf-ready.',
      deliverables: 'Manufacturer sourcing, product sampling, packaging design, brand identity, product photography',
      category: 'Product Development',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/64e9b7c34_generated_24ed540c.png',
    },
    {
      id: 'elemental-accents',
      title: 'Elemental Accents',
      description: 'Home décor product line — concept development, sourcing, custom packaging, and branded presentation.',
      fullDescription: 'Developed Elemental Accents, a home décor product line from concept through delivery. Managed sourcing, sampling, packaging design, and product photography. Created a premium branded experience from unboxing through display.',
      deliverables: 'Product concept, sourcing, packaging design, brand identity, product styling',
      category: 'Product Development',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/f16b2bfbf_generated_a4be94a2.png',
    },
    {
      id: 'product-3',
      title: 'Vero Skincare',
      description: 'Product line development for a skincare brand — from formulation oversight and packaging design to brand launch strategy.',
      fullDescription: 'Oversaw the development of Vero Skincare\'s inaugural product line. Coordinated between labs and manufacturers, designed product packaging and brand materials, and built the launch strategy. Delivered a cohesive, market-ready product collection.',
      deliverables: 'Product development oversight, packaging design, brand materials, launch strategy',
      category: 'Product Development',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/dd6d99bd5_generated_f447f54d.png',
    },
  ],
  creativeProduction: [
    {
      id: 'gabes-production',
      title: "Gabe's",
      description: 'E-commerce campaign production — managed shoot logistics, creative direction, and on-set coordination for seasonal product campaigns.',
      fullDescription: 'Managed end-to-end production for Gabe\'s seasonal e-commerce campaigns. Handled shoot logistics, creative direction, model coordination, and on-set leadership. Delivered high-volume visual content on tight timelines while maintaining brand consistency.',
      deliverables: 'Production management, creative direction, on-set coordination, campaign delivery',
      category: 'Creative Production',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/729016485_generated_a15b092e.png',
    },
    {
      id: 'creative-2',
      title: 'Aura Fashion Editorial',
      description: 'Fashion editorial shoot — creative direction, styling coordination, and production from concept through final delivery.',
      fullDescription: 'Led a fashion editorial shoot from concept to delivery. Managed creative direction, stylist and model coordination, location scouting, and on-set production. Delivered a polished visual story for both print and digital use.',
      deliverables: 'Creative direction, production management, styling coordination, post-production oversight',
      category: 'Creative Production',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/6afe33e2c_generated_9e283ca3.png',
    },
    {
      id: 'creative-3',
      title: 'Javo Studios — Commercial',
      description: 'Commercial production support — studio operations, shoot coordination, and post-production workflow management.',
      fullDescription: 'Provided production support for commercial shoots at Javo Studios. Managed studio operations, coordinated crew and talent, oversaw equipment and set logistics, and streamlined post-production workflows.',
      deliverables: 'Studio operations, crew coordination, shoot logistics, post-production management',
      category: 'Creative Production',
      image: 'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/b8630e857_generated_26f933b9.png',
    },
  ],
};

export const allProjects = [
  ...projectData.brandMarketing,
  ...projectData.websitesDigital,
  ...projectData.productDevelopment,
  ...projectData.creativeProduction,
];

export const featuredProjects = [
  projectData.brandMarketing[0],
  projectData.creativeProduction[0],
  projectData.productDevelopment[0],
  projectData.websitesDigital[0],
];