export const projectData = {
  brandMarketing: [
    {
      id: 'ja-timber-brand',
      title: 'JA Timber & Land Clearing',
      description: 'Full brand identity + website for a land-management company. Logo, signage, business cards, print materials, and a complete website build.',
      fullDescription: 'Built the full brand and web presence for JA Timber & Land Clearing from the ground up. Designed the logo and complete visual identity, produced yard signs, business cards, and vehicle graphics, then designed and built the website — all developed with a unified visual language that positions JA Timber as a credible, professional operation.',
      deliverables: 'Logo, brand guidelines, business cards, yard signage, vehicle graphics, full website design & build',
      category: 'Brand & Marketing',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/3df19de46_generated_image.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d6c7adc64_Screenshot2026-06-18at21802PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/e70648734_Screenshot2026-06-18at21600PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/bd1a30cd1_Screenshot2026-06-18at21734PM.png',
      ],
    },
    {
      id: 'the-window-boys',
      title: 'The Window Boys',
      description: 'Marketing and ongoing print materials for a residential and commercial window cleaning company, including vendor coordination.',
      fullDescription: 'Handled marketing and print materials for The Window Boys on an ongoing basis. Produced collateral and vehicle signage, and coordinated production with outside vendors to keep everything consistent and on-brand.',
      deliverables: 'Print materials, vehicle signage, marketing collateral, vendor coordination',
      category: 'Brand & Marketing',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/8ca35cba7_Truck_Placement.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/e6c761de1_Screenshot2026-06-18at100233PM.png',

      ],
    },
    {
      id: 'toscana-salon',
      title: 'Toscana Salon',
      description: 'Full brand and marketing buildout for a salon and wellness spa — brand foundation, website, and a recruitment and social strategy to fill chair rentals. In progress.',
      fullDescription: 'A complete brand and marketing buildout for Toscana Salon, a salon and wellness destination entering its next chapter. Defining the brand foundation — the owner\'s story, positioning, and voice — then building the website, a recruitment campaign to attract chair renters, and a social content strategy to grow the salon\'s presence and bring in both renters and clients.',
      deliverables: 'Brand foundation, positioning & voice, website design & build, recruitment campaign, social content strategy',
      category: 'Brand & Marketing',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/efef85518_Screenshot2026-06-19at104124AM.png',
      ],
    },
  ],
  appsDigital: [
    {
      id: 'pitchd',
      title: 'Pitchd',
      description: 'A launched app for creators and entrepreneurs to pitch ideas and get structured, actionable feedback. Concept, brand, UX, and full build — mine start to finish.',
      fullDescription: 'Pitchd is a live, launched app I built independently for creators and entrepreneurs to pitch their ideas and receive structured, actionable feedback. I owned the entire process: concept development, brand identity, UX/UI design, and the full build. Currently live and accepting users.',
      deliverables: 'App concept, UX/UI design, brand identity, full build, launch',
      category: 'Apps & Web',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/8457e8420_Screenshot2026-06-18at13046PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/c9ff60016_2-Home.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/0c4d81dd1_3-PersonalizedPlan.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/71d781f2e_4-Recording.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/4adc25930_5-DrillsPlaybook.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/71255d615_6-RealFeedback.png',
      ],
    },
    {
      id: 'myco',
      title: 'MyCo',
      description: 'An original app I built — a community platform designed to connect people around shared interests and real-world circles. Led concept, branding, UX, and build.',
      fullDescription: 'MyCo is an original app concept I developed independently. I led everything from the initial concept and brand identity to UX design, interface build, and launch. The app is built around the idea that belonging starts in communities — connecting people through shared interests, depth, and real-world circles, not endless feeds.',
      deliverables: 'App concept, brand identity, UX/UI design, build, launch — joinmyco.com',
      category: 'Apps & Web',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/969f0e9f5_Screenshot2026-06-18at20146PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d92e55c94_Screenshot2026-06-18at20035PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d9c37f2bf_Screenshot2026-06-18at20101PM.png',
      ],
    },
    {
      id: 'clarity-map',
      title: 'Clarity Map',
      description: 'An app prototype I designed and built to help users organize goals and gain personal clarity through a structured, visual framework.',
      fullDescription: 'Clarity Map is an app prototype I developed independently. I led the concept, brand identity, UX design, and prototype build. The app helps users organize goals and work through decisions with a structured, visual clarity framework. Currently in prototype phase.',
      deliverables: 'App concept, brand identity, UX/UI design, prototype',
      category: 'Apps & Web',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d935447e1_Screenshot2026-06-18at13104PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/a3646f051_Screenshot2026-06-18at100112PM.png',
      ],
    },
  ],
  productDevelopment: [
    {
      id: 'magic-rescue-stick',
      title: 'Magic Rescue Stick',
      description: 'Consumer product development — manufacturer sourcing, sampling, custom packaging, and brand identity.',
      fullDescription: 'Led the complete development cycle for Magic Rescue Stick from concept to production-ready. Found and vetted manufacturers, managed sampling rounds, designed custom packaging, and developed the brand identity and visual direction.',
      deliverables: 'Manufacturer sourcing, sampling management, packaging design, brand identity, visual direction',
      category: 'Product Development',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/3db7847f2_18D409F9-19FD-4852-A9D8-FF871EDBEF43.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/5ce1871e1_11E7C5CC-EF10-43FD-A9F5-55DF88C553B3.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/942594c13_395988BB-717B-4278-9E1B-7CA87823BA32.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/b12760564_ChatGPTImageFeb22026at03_40_08PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/22267e138_500F84B3-3E73-4B19-A9CD-9FD8CD1173FB.png',
      ],
    },
    {
      id: 'elemental-accents',
      title: 'Elemental Accents',
      description: 'Home décor product development — concept, sourcing, custom packaging, brand identity, and product styling.',
      fullDescription: 'Developed a minimal home décor product line from concept through production. Managed sourcing, oversaw sampling rounds, designed custom packaging, built the brand identity, and styled the products for photography. Previously sold on Amazon.',
      deliverables: 'Product concept, sourcing, sampling, packaging design, brand identity, product styling',
      category: 'Product Development',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/e3809c73e_IMG_6136.jpg',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/64e9b7c34_generated_24ed540c.png',
      ],
    },
  ],
  creativeProduction: [
    {
      id: 'gabes-production',
      title: "Gabes",
      description: "Large-scale e-commerce campaign production — coordinated shoot logistics, supported creative direction, and managed on-set operations for seasonal campaigns.",
      fullDescription: "Coordinated production on Gabes' high-volume seasonal e-commerce campaigns. Managed shoot logistics, crew coordination, model scheduling, and on-set operations. Supported creative direction to maintain brand consistency across a large volume of deliverables on tight timelines.",
      deliverables: 'Shoot logistics, crew & talent coordination, on-set production management, campaign delivery',
      website: 'https://gabesstores.com',
      category: 'Creative Production',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d598eb895_Screenshot2026-06-18at12814PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/a4e077dae_Screenshot2025-02-23at61452PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/74b05f16f_Screenshot2025-02-24at60129PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/ee441a5bb_Screenshot2025-02-24at60137PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/8fe87471f_Screenshot2026-06-18at102733PM.png',
      ],
    },
    {
      id: 'safran-everyday',
      title: 'Safran Everyday',
      description: 'Campaign shoot production for a women\'s lifestyle brand — shoot logistics, talent coordination, and on-set production management.',
      fullDescription: 'Managed campaign shoot production for Safran Everyday. Oversaw shoot logistics, talent and crew coordination, and on-set production from pre-production through final delivery. Delivered campaign imagery aligned with the brand\'s warm, editorial aesthetic.',
      deliverables: 'Shoot logistics, talent & crew coordination, on-set production management, campaign imagery delivery',
      website: 'https://safraneveryday.com',
      category: 'Creative Production',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/528296507_Screenshot2026-06-18at15113PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/f3fb1e09d_Screenshot2025-02-24at63542PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/c681a40fd_Screenshot2025-02-24at120219PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d16066000_Screenshot2025-02-24at63608PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/0c7ca6883_Screenshot2025-02-24at65340PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/26a6b692b_Screenshot2025-02-24at63514PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/30bddf6df_Screenshot2025-02-24at65404PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/2bb87765e_Screenshot2025-02-24at65332PM.png',
      ],
    },
    {
      id: 'pcna',
      title: 'PCNA',
      description: 'Campaign shoot production for a promotional products brand — product styling, shoot logistics, and on-set production management.',
      fullDescription: 'Managed campaign shoot production for PCNA, a leading promotional products company. Oversaw product styling, shoot logistics, and on-set production to deliver catalog and marketing imagery across their product lines.',
      deliverables: 'Product styling, shoot logistics, on-set production management, campaign imagery delivery',
      website: 'https://www.pcna.com',
      category: 'Creative Production',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/676e27d64_Screenshot2025-03-03at34721PM.png',
      ],
    },
    {
      id: 'helvak-apparel',
      title: 'Helvak Apparel',
      description: 'Campaign shoot production for a contemporary fashion brand — creative direction, talent coordination, and on-set production management.',
      fullDescription: 'Managed campaign shoot production for Helvak Apparel. Oversaw creative direction, talent and crew coordination, and on-set production from pre-production through final delivery. Delivered campaign imagery aligned with the brand\'s modern, editorial aesthetic.',
      deliverables: 'Creative direction, talent & crew coordination, shoot production, campaign imagery delivery',
      category: 'Creative Production',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/d9f3588b7_Screenshot2025-03-01at95020PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/5978c0654_Screenshot2025-03-01at94809PM.png',
      ],
    },
    {
      id: 'nulastin',
      title: 'Nulastin',
      description: 'Video production for a premium beauty brand — shoot logistics, crew coordination, and on-set production management.',
      fullDescription: 'Managed video production for Nulastin, a premium beauty and skincare brand. Oversaw shoot logistics, crew coordination, and on-set production to deliver polished video content for the brand\'s marketing campaigns.',
      deliverables: 'Video production, shoot logistics, crew coordination, on-set production management',
      category: 'Creative Production',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/5c0b96de4_Screenshot2026-06-19at110813AM.png',
      ],
    },
    {
      id: 'faggod-apparel',
      title: 'FAGGOD Apparel',
      description: 'Campaign shoot production for a bold streetwear brand — creative direction, talent coordination, and full production management.',
      fullDescription: 'Managed campaign shoot production for FAGGOD Apparel. Oversaw creative direction, talent and crew coordination, location, and on-set production from pre-production through final delivery. Delivered campaign imagery that matched the brand\'s unapologetic visual identity.',
      deliverables: 'Creative direction, talent & crew coordination, shoot production, campaign imagery delivery',
      category: 'Creative Production',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/8dfa342ae_Screenshot2025-02-24at62920PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/ac78593a1_Screenshot2025-02-24at124114PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/0a685284c_Screenshot2025-02-24at124121PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/a111669ae_Screenshot2025-02-24at124127PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/e017fe087_Screenshot2025-03-01at51300PM.png',
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/7d6912c00_Screenshot2025-02-24at70035PM.png',
      ],
    },
  ],
  socialContent: [
    {
      id: 'social-example-1',
      title: 'Social Content',
      description: 'Social content examples — upload your images here.',
      fullDescription: 'Social content examples.',
      deliverables: 'Social content',
      category: 'Social Content',
      images: [
        'https://media.base44.com/images/public/6a3416a0b2d81e218daa4cbb/729016485_generated_a15b092e.png',
      ],
    },
  ],
};

export const allProjects = [
  ...projectData.brandMarketing,
  ...projectData.appsDigital,
  ...projectData.productDevelopment,
  ...projectData.creativeProduction,
  ...projectData.socialContent,
];

export const featuredProjects = [
  projectData.brandMarketing[0],
  projectData.creativeProduction[0],
  projectData.productDevelopment[0],
  projectData.appsDigital[0],
];